### ISSUE TITLE
x509: certificate signed by unknown authority when executing apictl commands

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim-tooling#137]
**Description:**
When connecting to APIM instances and running CTL commands without `k`, the tool gives the following error 
`x509: certificate signed by unknown authority `

**Comment by uvindra** [comment]
Currently we do not have provision for providing the public certificate of the APIM server to the apictl. Since the apictl needs to deal with multiple environments, this means that we need to be able to provide a certificate per an environment.

Therefore including this as part of the _add_env_ command seems most suitable. We can specify a new flag such as _--cert_ in order provide the path of the .pem file. The command would then look like,

```
apictl add-env -e dev \
            --registration https://localhost:9444/client-registration/v0.15/register \
            --apim https://localhost:9444 \
            --token https://localhost:8244/token \
            --cert /home/user/public.pem
```

We will also need to store the cert in the ~/.wso2apictl folder as follows,

```
.wso2apictl
      |
      |--------- certs
                      |
                      |--------- <env>
                                       |
                                       |--------- <certname>.pem
```

Please give feedback on this

**Comment by uvindra** [comment]
After discussion we decided that the scope of this is more in the line of a new feature/capability. We do not have sufficient time to get this done and test it adequately for the 3.1.0 release.To overcome this short coming for the moment we will ship the wso2carbon public cert with the apictl. This will address the immediate issue raised in the ticket.

A new ticket will be created to track the requirement of maintaining certificates per environment.

**Comment by uvindra** [comment]
Fixed in 3.1.0 apictl

**Comment by nergizunal** [comment]
I am using apictl 3.2.0 but I still get this error. How can I solve that
